### ISSUE TITLE
`posts/` directory

### ISSUE THREAD

**Issue by joemasilotti** [sitepress/sitepress#21]
I'm using Sitepress for a blog so take this request with a grain of salt.

I'm used to having `_posts` or `src/posts` from Jekyll/Bridgetown. This is a special directory where I can add my blog posts and keep them separate from the more static pages on the site like `/about` or `/projects`.

The only two special things I know/care about are:

1. Removing `/posts` from the public URL
2. Replacing underscores with hyphens

For example, I'd like to access `posts/hello_world.html.md` via `/hello-world`, not `/posts/hello_world`.

**Comment by bradgessler** [comment]
Duplicate-ish of https://github.com/sitepress/sitepress/issues/22

Closing this (and continuing the conversation over there)
