### ISSUE TITLE
Move pages, like `/posts/foo_bar.html.erb` to `/foo-bar`

### ISSUE THREAD

**Issue by bradgessler** [sitepress/sitepress#22]
It's pretty common to have a folder full of posts, like `/posts/fizz_buzz.html.erb` and want to load those at a root namespace, like `/fizz-buzz`.

This will currently work:

```ruby
Sitepress.site.manipulate do |resource, root|
  if resource.request_path.starts_with? "/posts"
    # Remove the HTML format of index from the current resource level
    # so we can level it up.
    node = resource.node
    node.formats.remove ".html"
    node.remove
    root.add_child(node.name).formats.add asset: resource.asset, format: resource.format
  end
end
```

On the stand-alone site, this works if you put in `./config/site.rb` at the bottom (not inside the block) and restart the server.

The API is pretty cumbersome to make this all work, so instead have something like this:

```ruby
Sitepress.site.manipulate do |resource, root|
  resource.move_to root if resource.data.layout == "post"
  resource.data["moved"] = "Yeah, I moved it dude! This is some new data"
end
```

The manipulation pipeline is a pretty bad idea I think. Rather this should be run as a hook after the tree is built for the site hierarchy.

Additionally, this needs to reload between requests since a dev would reasonably want to interact with new resource locations as they play around with things.

I need to think of a name for the file where this lives, and of course a name for the hook method.

**Comment by joemasilotti** [comment]
I'll add this one addition: `dasherize`.

```ruby
root.add_child(node.name).formats.add asset: resource.asset, format: resource.format
```

This will expose `/posts/hello_world.html.erb` at `/hello-world`.

**Comment by bradgessler** [comment]
I have `move_to`, `remove`, and `copy_to` working in a branch at https://github.com/sitepress/sitepress/tree/site-manipulation-changes

Here's what the API will look like:

```ruby
site = Sitepress::Site.new
site.manipulate do |root|
  root.get("blog").children.each do |post|
    post.move_to root
  end
end
```

**Comment by bradgessler** [comment]
> I'll add this one addition: dasherize.

I'll let a helper handle that, like ActiveSupport.

That said, I do need an API that makes it possible to `build` a path of nodes. That might look like this:

```ruby
site = Sitepress::Site.new
site.manipulate do |root|
  root.get("blog").children.each do |post|
    post.move_to root.build(post.node.name.dasherize)
  end
end
```

**Comment by joemasilotti** [comment]
With the new code in `version-4` what's the recommended approach for updating the path to a moved link?

```ruby
Sitepress.site.manipulate do |root|
  root.get("articles").children.each do |article|
    article.move_to(root)
  end
end
```

This works great but I need to `#dasherize` the article's title. And

```ruby
root.add_child(article.node.name.dasherize)
```

doesn't seem to actually... do anything?

---

Also, totally OK if you respond with "use dashes in your filenames".

**Comment by bradgessler** [comment]
I need to document the `node ↔ resources ↔ formats` API much better! I do recommend renaming your files so that they're dasherized, under the principals that less indirection is better, but just for fun let's see if I can explain this in a way that could be helpful to a better API design or docs.

Here goes! First some "axioms"

* A site is made of a tree of nodes
* A node has many formats
* The combination of a node + format is a resource

Alrighty, now to get that back to solving your problem. When you call `root.add_child`, it creates a `node` with the dasherized name, but it doesn't have a `format` hanging off of it.

To do that you'd need to do something like this:

```ruby
root.add_child(article.node.name.dasherize).formats.add(:html, article.asset)
```

That should do it!

---

Alright, now let's talk better API designs. I think the `formats` concept is confusing with a `resource` in the public API. What I think makes more sense is an axiom like this:

* A site is made of a tree of nodes
* A node has many resources
* A resource has a format

Here's a few ideas for the API that would make it all work:

```ruby
root.add_child(name: article.node.name.dasherize, resource: article)
root.add_child(article.node.name.dasherize).add_resource article
root.add_child(article.node.name.dasherize).add_asset article.asset
root.children.build(article.node.name.dasherize).resources << article
root.create_node(article.node.name.dasherize).add_resource article
```

Not a fan of the name of those methods though because it's not something I associate with "moving web resources around". With that, I could update `move_to` and `copy_to` to work like this:

```ruby
Sitepress.site.manipulate do |root|
  root.get("articles").children.each do |article|
    article.move_to root.add_child(article.node.name.dasherize)
  end
end
```

Or allow for a resource to be renamed:

```ruby
Sitepress.site.manipulate do |root|
  root.get("articles").children.each do |article|
    article.node.name = article.node.name.dasherize
    article.move_to root
  end
end
```

That feels a bit awkward. If I'm trying to mimic `mv`, I would have something like this:

```ruby
Sitepress.site.manipulate do |root|
  root.get("articles").children.each do |article|
    article.rename_node(article.node.name.dasherize).move_to root
  end
end
```

I'm probably leaning more towards `Resource#rename_node` to keep this as a one-liner.

**Comment by joemasilotti** [comment]
What if the API was more OOP focused instead of functional?

```ruby
article.name = article.name.dasherize
article.parent = root
```

**Comment by bradgessler** [comment]
I like how that looks! The problem I'd run into now would be with this:

https://github.com/sitepress/sitepress/blob/072b9af63c6b40f393e50343428ad7c9afe7484f/sitepress-core/lib/sitepress/node.rb#L64-L67

When a node is moved, it has to be removed from this index, which I keep in a Hash:

https://github.com/sitepress/sitepress/blob/072b9af63c6b40f393e50343428ad7c9afe7484f/sitepress-core/lib/sitepress/node.rb#L103-L109

At some point I'd love to think about a better way to index all of the assets in this tree instead of a tree of hashes, as it works today. The most sensible thing would probably be to build the tree up, in the way that you show in your code above, then after the tree is built a mechanism would walk the entire tree and build out an index and "freeze" the whole thing.

**Comment by bradgessler** [comment]
Staring to work on this issue! I'm going to use this to lay out my initial thoughts so I don't get lost in my code.

The rendering pipeline needs to work something like this:

## 1. The NodeMapper class walks the directory and creates an initial tree from the folders and files it contains

I don't like how the NodeMapper is a constant in `Sitepress::Site`. That makes it unconfigurable. Ideally an instance of a NodeMapper is accessible at `Sitepress::Site#node_mapper` so it's configurable.

## 2. Once the initial node tree is built, let the end user manipulate it

This is where I need to remove the `child_nodes` hash above. Maintaining those references is a pain and makes the API awkward.

Additionally, it's weird moving a `Resource` to a `Node`, so think through that and clean it up.

Moving stuff around should be as simple as:

```ruby
blog = root.dig("blog")
blog.name = "buzz"
root.build_node("fizz").add_child(blog)
root.dig("fizz", "buzz") # This gives us the 'blog' node from above that we renamed.
```

During this phase of the build pipeline, there's little concern for performance on paths because we don't care about those yet and are not maintaining the references.

### 3. Path/route generation

Once the nodes are "manipulated" (or not), we have a tree that we can walk to generate routes. Maybe we'll call this the "RouteMapper" or something.

Anyway, this thing should walk the tree and generate routes that point to what will be loaded in a browser. Currently I'm calling these resources.

Something feels "off" about the relationship between Node, Format, and Resource. I need to think about this more and revisit this comment.

**Comment by bradgessler** [comment]
It's better to start by writing docs to the developer who will be using this. Here's what I've got so far based on some of @joemasilotti's recommendations above:

---

## Resource manipulation

The first thing to know about resource manpulatioon is that you shouldn't do it. The beauty of Sitepress is you know the path `/blog/my-post` can be found in `./pages/blog/my-post.html.md`. When you change the direct mapping between the request path and asset path, you create a level of indirection that makes it more difficult for people to find and edit content.

One more time, do everything you can to avoid manipulating resources! Just because you can do something doesn't mean you should.

Ok, fine so you want to manipuate resources. Maybe you're coming over from Middleman and you have a bunch of blog posts with URLs like `/blog/my-post` stuck in folders like `./source/blog/2010-12-22/brad-was-here.html.md`. Middleman accomplished this with a process known as resource manipulation.

Here's how you should not do it in Sitepress, not because you can't, but because you shouldn't:

```ruby
# Please do everything you can to avoid needing to do this.
site = Sitepress::Site.new(root_path: "/my/site")
site.manipulate do |root|
  blog = root.dig("blog")
  blog.children.each do |date_folder|
    post = date_folder.children.find { |resource| resource.formats.include? :html }
    post.parent = blog
    # PLEASE don't do this, just rename the underlying file instead to the slug and
    # remove the `slug` key from the post's Frontmatter.
    post.name = post.data.fetch("slug")
    post.data["layout"] = "blog-layout"
  end
end
```

When the `site.resources` method is called, the rules from `manipulate` are applied.

If you want to add or remove resources from the manipulate method, you can simply add a second `resources` argument to the `manipulate` block:

```ruby
site = Sitepress::Site.new(root_path: "/my/site")
site.manipulate do |resource, root|
  root.flatten.remove resource if resource.data["private"]
end
```

**Comment by bradgessler** [comment]
The `Resource` class now has the ability to change the `node` it belongs to. This will remove the `move_to` and `copy_to` APIs.

Here's what it would look like to move a blog post from `/my/blog-post` to `/my-post`:

```ruby
post = Sitepress.site.get("/blog/my-post")
post.node = Sitepress.site.root
```

**Comment by bradgessler** [comment]
After trying to manipulate a site without `move_to` and `copy_to`, I decided to add it back to make working with a site more intuitive (feels like working with files).

That means there's now two ways to manipulate a site's node structure:

1. Use the `Resource#move_to` and `Resource#copy_to` methods on resources or
2. Use the `Node#parent=` to manipulate the structure of the site.

I didn't implement `Node#move_to` or `Node#copy_to` since `Node#parent` can handle that. It might make sense in the future to add those methods, but for now we'll try this.

**Comment by MSchmidt** [comment]
Hi, I'm not sure what the status is. The comments suggest this should work already. But then it was added to the roadmap to I guess no?. Yet it's in the docs. But I don't get it to work either. Sorry I'm a bit lost. I have the same usecase as mentioned in the opening comment. I want to group my posts in a folder like `blog` but do not want to show `blog` in the URL of those posts.

**Comment by bradgessler** [comment]
Docs are at https://sitepress.cc/basics/traversal. I want to discourage people as much as possible for manipulating resources because it creates levels of indirection that generally end up being confusing and difficult to maintain down the road.

If the documents are confusing and don't work, could you work through it and open a PR at https://github.com/sitepress/website/blob/main/pages/basics/traversal.html.md with changes?
