### ISSUE TITLE
Public image URLs for `og:image`

### ISSUE THREAD

**Issue by joemasilotti** [sitepress/sitepress#27]
What's the best/recommended approach for sharing a public URL for an image?

I need to attach an `og:image` for sharing on Twitter and such.

```ruby
image_url("joe.jpg") # => http://://:/joe-3518a942b564376411a86cab7c042b4881fec174a43a4565ee4088adff204ce5.png
```

Which looks like the asset is found but it can't link to the host. Which makes sense, I've never set that anywhere.

Rails would have me setting `default_url_options` or something, right?

**Comment by bradgessler** [comment]
Yeah I need to get `default_url_options` to behave as expected and introduce the concept of environments into Sitepress.

For now, you can set `default_url_options` in a `./config/initializers/blah.rb` file. If you can't then that's another bug 😄

**Comment by joemasilotti** [comment]
Gotcha, thanks Brad!
