### ISSUE TITLE
[sitepress-rails] Changing the `DEFAULT_SITE_ROOT`

### ISSUE THREAD

**Issue by pinzonjulian** [sitepress/sitepress#29]
Hey @bradgessler !

I'm playing with Sitepress and I'm wondering if you'd consider making the `DEFAULT_SITE_ROOT` configurable during the Rails initialisation process. It would make it super easy to play around with different folder structures

**Comment by bradgessler** [comment]
Yeah, it's doable already... I think.

I'm watching Creative Galaxy with my kid now doing this from my phone, so this is 90% accurate 😂 

In your Rails project, you should have the `config/initializers/site.rb` file. 

Try changing the paths in that file, like this:

````Ruby
# Default layout for Sitepress pages
Sitepress.configure do |config|
  ## Change the root_path of the Sitepress site, or set to a different
  ## Sitepress instance.
  config.site = Sitepress::Site.new root_path: "your-desired-default-path"
end
````

Check out the source code at https://github.com/sitepress/sitepress/blob/main/sitepress-core/lib/sitepress/site.rb and you'll see there's a bunch of paths you can configure.

**Comment by pinzonjulian** [comment]
That did work! Thanks! 

I have a followup related question:

In the dummy app I'm building to try this out I have several subdomains with application code (e.g. `api.my-app.com`, `admin.my-app.com`) and I want Sitepress to sit at `my-app.com`. I imagine even having multiple Sitepress sites like `blog.my-app.com`, etc. 

When doing this, I'm finding that Sitepress is taking over all of my other routes and matching all root paths for al subdomains to the root path of the Sitepress site. For example

| Request  | Expected Response | Actual Response |
| ------------- | ------------- | ------------- |
| `api.my-app.com`  | `200 OK` -> `api.my-app.com`  | `200 OK` -> `my-app.com` |
| `admin.my-app.com/about`  | `404 Not found`  | `200 OK` -> `my-app.com/about` |

I dug down and found that hacking it a little bit I can get it to work:
```ruby
module Sitepress
  # Route constraint for rails routes.rb file.
  class RouteConstraint
    # [...] 

    def matches?(request)
      # -----------------------------------
      # 👀 added request.subdomain.blank?. It's a hack for something that should probably be configurable
      # -----------------------------------
      !!site.resources.get(request.path) && request.subdomain.blank?
    end
  end
end
```

```ruby
module ActionDispatch::Routing
  # I have no idea how or why this works this way [...]
  class Mapper
    # [...]

    # Hook up all the Sitepress pages
    # ----------------------
    # 👀 Note that this uses the newly edited constraint from above
    # ----------------------
    def sitepress_pages(controller: DEFAULT_CONTROLLER, action: DEFAULT_ACTION, root: false, constraints: Sitepress::RouteConstraint.new)
      # [...]
    end

    # Hook sitepress root up to the index of rails.
    def sitepress_root(controller: DEFAULT_CONTROLLER, action: DEFAULT_ACTION)
      if has_named_route? :root
        Rails.logger.warn "Sitepress tried to configured the 'root' route, but it was already defined. Check the 'routes.rb' file for a 'root' route or call 'sitepress_pages(root: false)'."
      else
       # ----------------------
       # 👀 pass the constraint down to the root method as well. 
       # Also note that the root method is not only used at the top level Rails application 
       # but also in an engine's routes as well       
       # ----------------------
        root controller: controller, action: action, constraints: Sitepress::RouteConstraint.new
      end
    end
  end
end

```

**Comment by pinzonjulian** [comment]
BTW, no rush! Get back to me whenever you're not busy. Family comes first!

**Comment by bradgessler** [comment]
Is the route helper within a subdomain constraint? It should look something like this:

```ruby
constraints(host: 'my-app.com') do
  sitepress_pages # or whatever you're using for the routes
end
```

**Comment by pinzonjulian** [comment]
No. It was like this:
```ruby
Rails.application.routes.draw do 
  sitepress_pages
  sitepress_root
  
  constraints subdomain: "api" do 
    # routes for api
  end

  constraints subdomain: "admin" do 
    # routes for admin
  end
end
```

**Comment by bradgessler** [comment]
It’s probably a route precedence issue. Put the subdomains above it and it should work (or constrain it)

Brad

**Comment by bradgessler** [comment]
Closing this issue since it's veered outside of the original reason it was opened.

**Comment by pinzonjulian** [comment]
Thanks for your help yesterday Brad. Reordering did help.
FWIW, I tried this in a fresh rails app without Sitepress and the same ordering issue arises so it's not Sitepress related. I do think it's a bit surprising though. I'll do some more digging. 

Also, above you said (emphasis is mine):
> In your Rails project, you **should** have the config/initializers/site.rb file.

However after installing `sitepress-rails` and running the generator there is no initializer. Just thought you should know because it's not mentioned in the docs.
