### ISSUE TITLE
Changing default site root to /blog

### ISSUE THREAD

**Issue by francoasdev** [sitepress/sitepress#32]
Hey Brad!

Just trying to start a project using sitepress, but can't find the initializer file in config/initializers/ to change the rooth path.
Should I configure it somewhere else, maybe creating the file?
Please let me know, this is exactly what I was looking for.
Thanks in advance!

**Comment by bradgessler** [comment]
Are you using this inside of rails or stand-alone?

The easiest thing to do is put the blog in `./content/blog` if you're trying to load it from `/blog` in a browser.

**Comment by francoasdev** [comment]
> Are you using this inside of rails or stand-alone?
> 
> The easiest thing to do is put the blog in `./content/blog` if you're trying to load it from `/blog` in a browser.

Inside a rails app.

Didn't imagine it was this easy. It's working already. Thanks!
I'm closing this Issue as it's now resolved.

**Comment by bradgessler** [comment]
Haha… I might use that as a quote on the website and link back to this issue.

**Comment by francoasdev** [comment]
> Haha… I might use that as a quote on the website and link back to this issue.

Thats gonna be helpful, for sure. No doubt that for many people /blog might be the right path for many apps.
