### ISSUE TITLE
Latest version of phlex does not work with sitepress out of the box

### ISSUE THREAD

**Issue by webmatze** [sitepress/sitepress#33]
I created a vanilla **sitepress** project and tried to create a simple **phlex** component.
But when I tried to render the component in a page I got the following error:

`ActionView::Template::Error: '#<TestComponent:0x00007fa47735de78 @name="Hello World">' is not an ActiveModel-compatible object. It must implement :to_partial_path.`

Sitepress Version: **3.2.1**
Phlex Version: **1.4.0**

I was able to fix the error by using the `'phlex-rails'` instead of `'phlex'` gem.

So it seems like the **phlex** gem by itself does not work with rails out of the box.

**Comment by bradgessler** [comment]
Thanks! https://github.com/sitepress/sitepress/commit/522b5ccd510b0e51c8952993a18e171fd01b3026 fixes this bug, which will be in the next release.
