### ISSUE TITLE
How to include other assets locations?

### ISSUE THREAD

**Issue by strzibny** [sitepress/sitepress#35]
How can I create other paths other than images and stylesheets for assets? Just dropping a new directory doesn't seem to work.

Would it be also possible to have a path at root (`/`)... I am asking because this would be necessery to move some of the sites over to Sitepress.

**Comment by strzibny** [comment]
Okay I might have found it. There is this in `assets/config`:

```
//= link_tree ../images
//= link_directory ../stylesheets .css
//= link_directory ../javascripts .js
```

**Comment by strzibny** [comment]
One option is to just move the files after the build e.g. have a Rakefile that runs two tasks, but I am curious if this is not solved by Sitepress. Note I am talking about standalone Sitepress as we have `public/` in Rails.

**Comment by bradgessler** [comment]
I'm probably going to remove Sprockets (and all other asset pipelines) and recommend that assets be put in the `./pages` directory.

For example, `./pages/images` could have all images and be linked to via `/images/foo.png`

This approach could be a lot easier since everything in pages ends up being built out to the ./build directory.

Are you trying to fingerprint the assets?

**Comment by strzibny** [comment]
I mostly wasn't but since this is supported, I decided to fingerprint them. I feel there might be assets you want to fingerprint and assets you might not need to (and prefer not to).

**Comment by bradgessler** [comment]
If you don't want to fingerprint assets, just throw them into `./pages/images`, `./pages/foo`, etc. and you won't need to worry about a separate script that moves the files.

If you prefer to keep them in a separate directory, then I would recommend just copying them over in a script.

**Comment by strzibny** [comment]
That's completely enough, thanks for the tip.
