### ISSUE TITLE
No Method Error using Render_layout

### ISSUE THREAD

**Issue by JoshLedgard** [sitepress/sitepress#39]
I'm working to create a blog post with a blog_post layout that calls the parent "static" layout I've created. But I run into this: 

https://images.kickofflabs.com/Sr61JZ3x

The project is structured like this: https://images.kickofflabs.com/7tw87xt3

Not sure what's wrong as it seems like I'm following the docs here. 

Thanks! 
Josh

**Comment by bradgessler** [comment]
This helper isn't being loaded: https://github.com/sitepress/sitepress/blob/remove-singleton/sitepress-rails/rails/lib/generators/sitepress/install/templates/helpers/page_helper.rb#L24-L28

Make sure that exists in your `PagesHelper` file (or wherever you have it) and it should work.
