### ISSUE TITLE
Markdown pages not rendered

### ISSUE THREAD

**Issue by collimarco** [sitepress/sitepress#42]
Steps to reproduce:

1. Install sitepress in a Rails app as described in the docs
2. Create a folder`app/content/pages/blog` and add some markdown files (e.g. `example-post.md`)
3. Now visit `example.com/blog/example-post` and you get 404
4. Even if you visit `example.com/blog/example-post.md` (with the extension) you get the raw markdown file, instead of a rendered page (with layout and html)

Can you please help? How do I configure sitepress to render those `md` files? @bradgessler

**Comment by collimarco** [comment]
I just need to add a markdown handler and it works:

https://answers.abstractbrain.com/how-to-render-markdown-views-in-rails/

**Comment by bradgessler** [comment]
I added a page to the documentation at https://sitepress.cc/basics/template-handlers to make it more apparent to future Sitepress users how they can add whatever templating engines they need to their project.
