### ISSUE TITLE
Adding `markdown-rails` gem breaks site

### ISSUE THREAD

**Issue by joemasilotti** [sitepress/sitepress#44]
I'm back to exploring Sitepress again after getting fed up with Bridgetown's long build times.

I'm working with a completely stock Rails 7.1 app. I can route `app/content/pages/hello-world.html` to `/hello-world` correctly.

But when I add the `markdown-rails` gem and add `.md` to the filename, it 404s.

Am I doing something wrong or miss a configuration? Or is this a Rails 7.1 issue?

**Comment by JoshAntBrown** [comment]
I'm getting the same, though I'm using the standalone approach without embedding in a Rails application.

The 404 page that the standalone server renders has the following table:

Request path | Asset path | Mime type
-- | -- | --
/ | pages/index.html.erb | text/html
/test | pages/test.html.erb | text/html
/stack.html.md | pages/stack.html.md | text/markdown

Note that `/test` works fine, but `/stack` doesn't get mapped as expected (and using the route it suggests gives you the raw file content not the rendered result)

**Comment by bradgessler** [comment]
@JoshAntBrown pin markdown-rails to 1.0 in your Gemfile like this:

```
gem "markdown-rails", "~> 1.0"
```

And try again. If that works I can get a fix out so this works with 2.0.

**Comment by bradgessler** [comment]
@joemasilotti run `bundle show` and paste the contents in here so I can check gem compatibility.

**Comment by bradgessler** [comment]
Working on a patch for markdown-rails 2.0 at https://github.com/sitepress/markdown-rails/commit/6a9b6817e8188a069ffe8ec30373beaa38564b55 that will make `.md` work without running the installer.

This will make it compatible with 1.0, which means this breakage should go away when 2.0 is installed.

**Comment by bradgessler** [comment]
Released markdown-rails 2.0.1 ... which should be compatible with 1.0. Try updating to that and report any issues.

**Comment by diegotoral** [comment]
Just upgraded markdown-rails to 2.0.1 and it worked like a charm! 👌 

Thank you for the quick help and this awesome project @bradgessler!

**Comment by joemasilotti** [comment]
It works! Thanks Brad. Now I just have to figure out how to get `.markerb` files working. :D
