### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by bradgessler** [sitepress/sitepress#5]
Sitepress was built originally to work for a Rails 4.2 website. The gem should be integrated with Rails 5 to support more widespread adoption. To fix this:

1.   [x]  **Get the build of the SItepress gem passing** - Sitepress will boot with Rails 5 from the master branch, but there are threading issues with the development environment (see below)

2.   [x]  **Wire up Appraisal to run test suites on Travis CI against Rails 5 gems** - Appraisal gem work is happening in the [appraisal branch](https://github.com/sitepress/sitepress/tree/appraisals), but it won't pass on TravisCI yet because I'm waiting on https://github.com/thoughtbot/appraisal/pull/125 to close so that travis CI passes. I ran into issues specifying Gemfiles in `.travis.yml` while trying to use my custom branch of appraisal.

3.
    [ ] **Fix threading issues in Rails 5 development mode** - In development mode, the Sitepress rails gem builds the site hierarchy initially in the [rails router as a route constraint](https://github.com/sitepress/sitepress/blob/master/sitepress-rails/lib/sitepress/route_constraint.rb#L4). For performance reasons, we enable the cache so that subsequent calls to `Sitepress.site` don't have to rebuild the hierarchy every time during that request. Unfortunately `Sitepress.site` is a global variable, so if two requests are fired off to the rails server the `Sitepress.site.cache_resources` value can be put int a state where its `true`, which disables the reloading of the site hierarchy between requests meaning the use won't see their changes reflected.
    
    I suspect the issue happens in Rails 5 because `Rack::Lock` was removed and replaced with more granular locks. Either `Sitepress.site` needs to lock or a new `Sitepress.site` hierarchy should be built per request.

    The current approach to setting the cache value for `Siterpess.site` is via the `Sitepress::Middleware::RequestCache` loaded via a [rack middleware](https://github.com/sitepress/sitepress/blob/master/sitepress-core/lib/sitepress/middleware/request_cache.rb). That way when the route constraint in Rails hits Sitepress.site, the hierarchy is generated and used downstream by controller and views. When the request is completed the cache value is set back to its original value. If there's a way to not have to load this middleware (e.g. can we not have a global that's loaded for the route constraints?) that might be the way to go, but would probably use more memory. The other option is that we put a Mutex around the call block in development mode and get our coarse lock behavior we had in Rails 4 with `Rack::Lock`.

Once these issues are resolved we'll be able to release Sitepress to Rails 5.

**Comment by thoughtless** [comment]
`Sitepress::Compiler#compile` seems to have the same issue as you described for the rack middleware.

https://github.com/sitepress/sitepress/blob/b30a7352ed1c2c163d200b710857a4519b3fc4d2/sitepress-cli/lib/sitepress/compiler.rb#L15

**Comment by thoughtless** [comment]
So far I've only taken a brief look at the related code, but I think the easiest fix for the caching and threading issues is this:

1) Change all the "internal" code to always cache. For example, never have this class check `cache_resources` or call `clear_resources_cache`: https://github.com/sitepress/sitepress/blob/51983ba2256e9e5b4e20db90071ac295c7af2c1d/sitepress-core/lib/sitepress/site.rb#L107

2) Expose a new method: `Sitepress::Site#clear_cache`. This could just be `clear_resources_cache`, though it may need to be expanded.

3) Only the rack middleware will care about the value of `@site.cache_resources`. In fact, you could remove this this config from `Sitepress::Site` entirely and just have it as either Rails config or another argument to the Middleware. I prefer making it an argument to the Middleware's initializer. If the config option is true, then we do nothing. If the config option is false, then we call `@site.clear_cache` before each request.

4) Change all code within `Sitepress::Site` that references the instance variables used for caching (i.e. `@_resources`) to use a Mutex. Most likely the only two public methods that this would affect are `Sitepress::Site#clear_cache` and `Sitepress::Site#resources`.

**Comment by bradgessler** [comment]
The `Sitepress::Resources` collection has to be cached for performance reasons when a page references itself. For example, the call

```haml
---
title: Test page
---

%h1==Listing all #{site.resources.size} resources
%ul
  -site.resources.each do |page|
    =link_to page.request_path, page.data["title"]
```

needs to have a cached `#resources` method to avoid n+1 problems every time the method is called.

I like the idea of removing the caching complexity from `Sitepress::Site#resources` and just always cache it. It lessons that chances of a performance regression if somebody forgets to set the cache.

If that approach is taken, the `Sitepress.site` class method could configure and return an instance of a new `Sitepress::Site` object on each request and negate the need for a Mutex in a development environment. Each request would just be getting a new instance of a site.

In a production environment the `Sitepress.site` method would be configured to only serve up one instance of a `Sitepress::Site` object for all requests.

**Comment by bradgessler** [comment]
https://github.com/thoughtbot/appraisal/pull/125 was merged, a gem was cut, and now https://travis-ci.org/sitepress/sitepress/builds/223668638 is passing for Rails 4 and 5.
