### ISSUE TITLE
Slim pages are not rendering / not found

### ISSUE THREAD

**Issue by candland** [sitepress/sitepress#58]
I'm using slim in the project and the slim layouts render fine, but if I add a page `content/pages/test-slim.html.slim` 

Going to `/test-slim.html` goes to not found / no route matches.
Going to `/test-slim.html.slim` downloads the file.

I'm using 4.0.2 with markdown set up (works, as well as erb).

Rails 7.1.0

Installed following the docs, but I did have to override the controller to skip some actions I have in `ApplicationController`.

```ruby
class SiteController < ApplicationController
  include Sitepress::SitePages

  skip_scoped_check :show
  skip_authorized_check :show
end

# in routes
sitepress_pages root: true, controller: "site"
```

Another interesting thing, it shows up in `PageModel.all` and links to it, but with the `.slim` extension.

Any idea what I'm missing?

**Comment by candland** [comment]
Found what's going on. For some reason slim isn't being added to `ActionView::Template::Handlers.extensions`. Interesting that it's rendering okay outside of Sitepress.

When this runs, it's not there and Sitepress doesn't register any `.slim` pages.

https://github.com/sitepress/sitepress/blob/761b29141b2ff5a3070acd70245902461cebafb8/sitepress-rails/lib/sitepress/engine.rb#L55

**To Fix**

Added `config/initializers/sitepress.rb`.

```ruby
Rails.configuration.to_prepare do
  ActionView::Template::Handlers.extensions << :slim
end
```

**Comment by bradgessler** [comment]
Closing since this is likely related to https://github.com/sitepress/sitepress/issues/58.

If that release doesn't fix this issue this can be re-opened.
